### ISSUE TITLE
Kanban Board Setup 

### ISSUE THREAD

**Issue by jmontanholi** [jmontanholi/react-space-hub#25]
## This project's team only has two members:
* [Alex Arturo Guzman Cruz](https://github.com/ArthurGC
)
* [João Vítor Montanholi Nunes](https://github.com/jmontanholi)

### Here is the project [link](https://github.com/jmontanholi/react-space-hub/projects/1)

![](https://media2.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif)

**Comment by AshakaE** [comment]
### Hi @jmontanholi  🙋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request ❌ 

You have submitted a project, that does not list the team members on this project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AshakaE** [comment]
### Hi @jmontanholi  🙋‍♀️, 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 😄 


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
